#ifndef ANRI_BUTTON_EVENT_TYPE_H
#define ANRI_BUTTON_EVENT_TYPE_H

enum InputEventType
{
    KB_KEY_UP, KB_KEY_DOWN,

    PAD_BUTTON_UP, PAD_BUTTON_DOWN,
    PAD_AXIS_X, PAD_AXIS_Y,

    INPUT_EVENT_UNKNOWN
};

#endif