#ifndef ANRI_INPUT_VALUE_H
#define ANRI_INPUT_VALUE_H

enum InputValue
{
    // Keyboard
    KB_ARROW_UP, KB_ARROW_DOWN, KB_ARROW_LEFT, KB_ARROW_RIGHT,
    KB_SPACE, KB_ENTER,

    // Gamepad
    PAD_A, PAD_B, PAD_X ,PAD_Y,
    PAD_DPAD_UP, PAD_DPAD_DOWN, PAD_DPAD_LEFT, PAD_DPAD_RIGHT,
    PAD_RIGHT_BUTTON, PAD_LEFT_BUTTON, PAD_RIGHT_TRIGGER, PAD_LEFT_TRIGGER,
    PAD_LEFT_STICK, PAD_RIGHT_STICK,
    PAD_START, PAD_BACK,

    INPUT_VALUE_UNKNOWN
};

#endif